{
	"sub": "为医院、医生、医药、医保等行业客户提供互联网医疗服务解决方案的科技服务型公司！",
	"function": [{
		"title": "首页",
		"main": "",
		"sub": "/hos/dashboard/images/description/sub_icon_sy.png",
		"id": "sy",
		"suffix": "0",
		"enable": "1",
		"sort": 0,
		"remark": ""
	}, {
		"title": "公司介绍",
		"main": "/hos/dashboard/images/description/main_icon_gsjs.png",
		"sub": "/hos/dashboard/images/description/sub_icon_gsjs.png",
		"id": "gsjs",
		"suffix": "1",
		"enable": "1",
		"sort": 1,
		"remark": ""
	}, {
		"title": "团队介绍",
		"main": "/hos/dashboard/images/description/main_icon_tdjs.png",
		"sub": "/hos/dashboard/images/description/sub_icon_tdjs.png",
		"id": "tdjs",
		"suffix": "1",
		"enable": "1",
		"sort": 2,
		"remark": ""
	}, {
		"title": "发展历程",
		"main": "/hos/dashboard/images/description/main_icon_fzlc.png",
		"sub": "/hos/dashboard/images/description/sub_icon_fzlc.png",
		"id": "fzlc",
		"suffix": "1",
		"enable": "1",
		"sort": 3,
		"remark": ""
	}, {
		"title": "公司战略",
		"main": "/hos/dashboard/images/description/main_icon_gszl.png",
		"sub": "/hos/dashboard/images/description/sub_icon_gszl.png",
		"id": "gszl",
		"suffix": "1",
		"enable": "1",
		"sort": 4,
		"remark": ""
	}, {
		"title": "产业结构",
		"main": "/hos/dashboard/images/description/main_icon_cyjg.png",
		"sub": "/hos/dashboard/images/description/sub_icon_cyjg.png",
		"id": "cyjg",
		"suffix": "1",
		"enable": "0",
		"sort": 5,
		"remark": ""
	}, {
		"title": "公司荣誉",
		"main": "/hos/dashboard/images/description/main_icon_gsry.png",
		"sub": "/hos/dashboard/images/description/sub_icon_gsry.png",
		"id": "gsry",
		"suffix": "1",
		"enable": "1",
		"sort": 6,
		"remark": ""
	}, {
		"title": "公司产品",
		"main": "/hos/dashboard/images/description/main_icon_gscp.png",
		"sub": "/hos/dashboard/images/description/sub_icon_gscp.png",
		"id": "gscp",
		"suffix": "1",
		"enable": "1",
		"sort": 7,
		"remark": ""
	}]
}
