{
	"info": [{
		"title": "互联网医院",
		"background": "/hos/dashboard/images/description/gscp_background_hlwyy.png",
		"label": [{
			"title": "智慧门诊",
			"sort": 0,
			"remark": ""
		}, {
			"title": "智慧住院",
			"sort": 1,
			"remark": ""
		}, {
			"title": "统一支付对账",
			"sort": 2,
			"remark": ""
		}],
		"caption": [{
			"title": "构建覆盖诊前、诊中、诊后的线上线下一体化医疗服务模式",
			"sort": 0,
			"remark": ""
		}, {
			"title": "在线开展部分常见病、慢性病复诊，拓展了医疗服务半径",
			"sort": 1,
			"remark": ""
		}, {
			"title": "打造符合多场景互联网诊疗业务的同时，实现真正意义上的线下业务线上化",
			"sort": 2,
			"remark": ""
		}],
		"sort": 0,
		"remark": ""
	}, {
		"title": "数字门诊",
		"background": "/hos/dashboard/images/description/gscp_background_szmz.png",
		"label": [{
			"title": "流程优化",
			"sort": 0,
			"remark": ""
		}, {
			"title": "便捷化",
			"sort": 1,
			"remark": ""
		}, {
			"title": "智能导诊",
			"sort": 2,
			"remark": ""
		}],
		"caption": [{
			"title": "搭建基于大数据的官方信息门户端，涵盖患者就诊的服务全过程",
			"sort": 0,
			"remark": ""
		}, {
			"title": "对就诊全流程进行优化设计和构建体系，“以患者为中心”对医院门诊就诊流程进行优化重组",
			"sort": 1,
			"remark": ""
		}, {
			"title": "将看诊流程以便捷化、智能化的方式整合，实现智能导医数字化门诊",
			"sort": 2,
			"remark": ""
		}],
		"sort": 1,
		"remark": ""
	}, {
		"title": "特色科室",
		"background": "/hos/dashboard/images/description/gscp_background_tsks.png",
		"label": [{
			"title": "生命周期管理",
			"sort": 0,
			"remark": ""
		}, {
			"title": "诊后管理",
			"sort": 1,
			"remark": ""
		}],
		"caption": [{
			"title": "通过使用互联网、人工智能的技术为诊后患者提供系统的诊后管理。",
			"sort": 0,
			"remark": ""
		}, {
			"title": "从用药依从性干预、单病种解决方案等服务，延伸至导医、导诊、慢病保险等",
			"sort": 1,
			"remark": ""
		}, {
			"title": "全方位一体化的诊后服务，为患者打造全生命周期管理。",
			"sort": 2,
			"remark": ""
		}],
		"sort": 2,
		"remark": ""
	}, {
		"title": "智慧住院",
		"background": "/hos/dashboard/images/description/gscp_background_zhzy.png",
		"label": [{
			"title": "结算优化",
			"sort": 0,
			"remark": ""
		}, {
			"title": "流程简化",
			"sort": 1,
			"remark": ""
		}],
		"caption": [{
			"title": "优化医疗服务流程，实现患者信息的全面、准确、及时共享",
			"sort": 0,
			"remark": ""
		}, {
			"title": "打破传统入院、出院结算模式，实现“数据多跑路、患者少跑腿",
			"sort": 1,
			"remark": ""
		}, {
			"title": "真正做到“零距离”服务，极大地简化了出入院流程，真正实现“一站式”出入院服务",
			"sort": 2,
			"remark": ""
		}],
		"sort": 3,
		"remark": ""
	}, {
		"title": "鲁康通",
		"background": "/hos/dashboard/images/description/gscp_background_lkt.png",
		"label": [{
			"title": "智能导诊",
			"sort": 0,
			"remark": ""
		}, {
			"title": "流程优化",
			"sort": 1,
			"remark": ""
		}, {
			"title": "便捷化",
			"sort": 2,
			"remark": ""
		}],
		"caption": [{
			"title": "努力为广大人民群众提供高质、可及的健康管理服务，用心守护全民健康",
			"sort": 0,
			"remark": ""
		}, {
			"title": "以用户健康为中心的服务宗旨，拓展传统医疗服务、医药流通、健康保险、医疗信息化等行业的边界",
			"sort": 1,
			"remark": ""
		}, {
			"title": "集医疗服务、健康管理服务、康养服务、保险服务、数字营销服务、电商服务为一体",
			"sort": 2,
			"remark": ""
		}],
		"sort": 4,
		"remark": ""
	}, {
		"title": "智慧服务管理平台",
		"background": "/hos/dashboard/images/description/gscp_background_zhfwglpt.png",
		"label": [{
			"title": "便捷、高效、优质",
			"sort": 0,
			"remark": ""
		}, {
			"title": "提高服务质量",
			"sort": 1,
			"remark": ""
		}, {
			"title": "信息化管理",
			"sort": 2,
			"remark": ""
		}],
		"caption": [{
			"title": "通过信息化技术和互联网技术，对医院的服务进行全面管理和优化",
			"sort": 0,
			"remark": ""
		}, {
			"title": "帮助医院提高服务效率、提升服务质量、改善患者体验，实现医疗信息化管理",
			"sort": 1,
			"remark": ""
		}, {
			"title": "医院智慧服务管理平台可以为患者提供更加便捷、高效、优质的医疗服务",
			"sort": 2,
			"remark": ""
		}],
		"sort": 5,
		"remark": ""
	}]
}
