{
	"function": [{
		"title": "首页",
		"main": "",
		"sub": "/hos/dashboard/images/partner/sub_icon_sy.png",
		"id": "sy",
		"suffix": "0",
		"enable": "1",
		"sort": 0,
		"remark": ""
	}, {
		"title": "医疗合作",
		"main": "/hos/dashboard/images/partner/main_icon_ylhz.png",
		"sub": "/hos/dashboard/images/partner/sub_icon_ylhz.png",
		"id": "ylhz",
		"suffix": "1",
		"enable": "1",
		"sort": 1,
		"remark": ""
	}, {
		"title": "战略合作",
		"main": "/hos/dashboard/images/partner/main_icon_zlhz.png",
		"sub": "/hos/dashboard/images/partner/sub_icon_zlhz.png",
		"id": "zlhz",
		"suffix": "1",
		"enable": "1",
		"sort": 2,
		"remark": ""
	}, {
		"title": "科研机构",
		"main": "/hos/dashboard/images/partner/main_icon_kyjg.png",
		"sub": "/hos/dashboard/images/partner/sub_icon_kyjg.png",
		"id": "kyjg",
		"suffix": "1",
		"enable": "1",
		"sort": 3,
		"remark": ""
	}, {
		"title": "经典案例",
		"main": "/hos/dashboard/images/partner/main_icon_jdal.png",
		"sub": "/hos/dashboard/images/partner/sub_icon_jdal.png",
		"id": "jdal",
		"suffix": "1",
		"enable": "1",
		"sort": 4,
		"remark": ""
	}, {
		"title": "医联山东",
		"main": "/hos/dashboard/images/partner/main_icon_ylsd.png",
		"sub": "/hos/dashboard/images/partner/sub_icon_ylsd.png",
		"id": "ylsd",
		"suffix": "1",
		"enable": "1",
		"sort": 5,
		"remark": ""
	}]
}
