{
	"caption": {
		"top": "口碑源于客户的成功验证<br>截止{0}年",
		"main": "已经合作过100+家知名企业 ",
		"bottom": "覆盖教育、保险、医美、企业服务等多个领域<br>期待您的加入..."
	},
	"info": [{
		"logo": "/hos/dashboard/images/logo/business/gsyh.png",
		"sort": 0,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/zsyh.png",
		"sort": 1,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/zfb.png",
		"sort": 2,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/yxkj.png",
		"sort": 3,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/zgyz.png",
		"sort": 4,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/hjt.png",
		"sort": 5,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/lc.png",
		"sort": 6,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/zgtp.png",
		"sort": 7,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/jsyh.png",
		"sort": 8,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/ss.png",
		"sort": 9,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/ytjf.png",
		"sort": 10,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/sy.png",
		"sort": 11,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/jnzwfw.png",
		"sort": 12,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/aljk.png",
		"sort": 13,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/wx.png",
		"sort": 14,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/qlyh.png",
		"sort": 15,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/hs.png",
		"sort": 16,
		"remark": ""
	}, {
		"logo": "/hos/dashboard/images/logo/business/ltyl.png",
		"sort": 17,
		"remark": ""
	}]
}
